export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ESTABLISH_SOCKET = "ESTABLISH_SOCKET";
export const DESTABLISH_SOCKET = "DESTABLISH_SOCKET";